# Generated by Django 4.1.1 on 2023-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0004_columngroup_remove_column_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collections', to='djangobase.collection'),
        ),
    ]
