# Generated by Django 4.1.1 on 2023-03-15 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0005_column_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='djangobase.collection'),
        ),
        migrations.AlterField(
            model_name='column',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_columns', to='djangobase.collection'),
        ),
    ]
