# Generated by Django 4.1.1 on 2023-03-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0006_column_collection_alter_column_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_type',
            field=models.CharField(blank=True, default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='column',
            name='column_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='djangobase.columngroup'),
        ),
    ]
