# Generated by Django 4.1.1 on 2023-03-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0007_column_column_type_alter_column_column_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='foreign_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_columns', to='djangobase.collection'),
        ),
    ]
