# Generated by Django 4.1.1 on 2023-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0010_remove_column_collection_remove_column_column_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['number'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['number'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AlterModelOptions(
            name='columngroup',
            options={'ordering': ['number'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AddField(
            model_name='collection',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='column',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='columngroup',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
