# Generated by Django 4.1.1 on 2023-03-25 13:26

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0011_alter_collection_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['number'], 'verbose_name': 'Collections', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='columngroup',
            options={'ordering': ['number'], 'verbose_name': 'Column group', 'verbose_name_plural': 'Column groups'},
        ),
        migrations.RemoveField(
            model_name='column',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='column',
            name='column_groups',
        ),
        migrations.RemoveField(
            model_name='columngroup',
            name='collections',
        ),
        migrations.CreateModel(
            name='ColumnGroupColumnRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('column', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.column')),
                ('column_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.columngroup')),
            ],
            options={
                'ordering': ['column_order'],
            },
        ),
        migrations.CreateModel(
            name='CollectionColumnRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.collection')),
                ('column', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.column')),
            ],
            options={
                'ordering': ['column_order'],
            },
        ),
        migrations.CreateModel(
            name='CollectionColumnGroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_group_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.collection')),
                ('column_group', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.columngroup')),
            ],
            options={
                'ordering': ['column_group_order'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='column_groups',
            field=models.ManyToManyField(blank=True, related_name='collections', through='djangobase.CollectionColumnGroupRelation', to='djangobase.columngroup', verbose_name='Column groups'),
        ),
        migrations.AddField(
            model_name='collection',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='collections', through='djangobase.CollectionColumnRelation', to='djangobase.column', verbose_name='Colums'),
        ),
        migrations.AddField(
            model_name='columngroup',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='column_groups', through='djangobase.ColumnGroupColumnRelation', to='djangobase.column', verbose_name='Columns'),
        ),
    ]
