# Generated by Django 4.1.1 on 2023-03-25 17:51

import adminsortable.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0013_alter_collection_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier_type', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id_type', models.CharField(blank=True, max_length=255, null=True)),
                ('old_id', models.CharField(blank=True, max_length=255, null=True)),
                ('guid', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('unpublished', models.DateTimeField(blank=True, default=datetime.datetime(2099, 12, 31, 0, 0), null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('color_hex', models.CharField(default='rgba(127, 127, 127, .5)', max_length=255)),
                ('background_color_hex', models.CharField(default='transparent', max_length=255)),
                ('tint_color_hex', models.CharField(default='rgba(127,127,127, .5)', max_length=255)),
                ('primary_color_hex', models.CharField(default='rgba(127,127,127, .5)', max_length=255)),
                ('popularity', models.FloatField(default=0)),
                ('streams', models.FloatField(default=0)),
                ('followers', models.FloatField(default=0)),
                ('consumers', models.FloatField(default=0)),
                ('consumes', models.FloatField(default=0)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CollectionGroupCollectionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('collection', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.collection')),
                ('collection_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.collectiongroup')),
            ],
            options={
                'ordering': ['collection_order'],
            },
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_groups', through='djangobase.CollectionGroupCollectionRelation', to='djangobase.collection', verbose_name='Collection groups'),
        ),
    ]
