# Generated by Django 4.1.1 on 2023-03-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0014_collectiongroup_collectiongroupcollectionrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangobase.website'),
        ),
    ]
