# Generated by Django 4.1.1 on 2023-03-26 09:19

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobase', '0015_collectiongroup_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeatureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_order', models.PositiveIntegerField(default=0)),
                ('feature', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.feature')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.website')),
            ],
            options={
                'ordering': ['feature_order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCollectionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_order', models.PositiveIntegerField(default=0)),
                ('collection', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.collection')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobase.feature')),
            ],
            options={
                'ordering': ['collection_order'],
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='features', through='djangobase.FeatureCollectionRelation', to='djangobase.collection'),
        ),
        migrations.AddField(
            model_name='website',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='websites', through='djangobase.WebsiteFeatureRelation', to='djangobase.feature', verbose_name='features'),
        ),
    ]
